FROM node:24.19.0-bookworm@sha256:4196d66a565c6f195728d9952f161f4adfe2ad753052a08b7ec7f1c5a6bda42b

COPY . /app
RUN chmod u+x /app/entrypoint.sh

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb
RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

CMD ["/app/entrypoint.sh"]
