FROM node:24.20.0-bookworm@sha256:be23f54a88d34e8824c741b19b91064094f92c1c97b194144bfc8b50d67258e2

COPY . /app
RUN chmod u+x /app/entrypoint.sh

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb
RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

CMD ["/app/entrypoint.sh"]
