FROM node:24.21.0-bookworm@sha256:6dac556d980b7f0e5498d08f08cee0ca67798b4ad6c23964a9214920e67758d0

COPY . /app
RUN chmod u+x /app/entrypoint.sh

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb
RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

CMD ["/app/entrypoint.sh"]
