FROM node:24.15.0-bookworm@sha256:f22d6a1f082c02f292e86929b5b0442ac2e5eaf438a5dea9b1566601c3e05940

COPY . /app
RUN chmod u+x /app/entrypoint-mongo.sh

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb
RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional

CMD ["/app/entrypoint-mongo.sh"]
