version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/aoe-data-analytics"
      - "/aoe-data-services"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directories:
      - "/aoe-infra"
      - "/aoe-semantic-apis"
      - "/aoe-streaming-app"
      - "/aoe-web-backend"
      - "/aoe-web-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker"
    directories:
      - "/aoe-data-analytics/service-etl-processor"
      - "/aoe-data-services/oaipmh-provider/"
      - "/aoe-semantic-apis/docker"
      - "/aoe-streaming-app/docker"
      - "/aoe-web-backend/docker"
      - "/aoe-web-frontend/docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
