export const koodistoSources = {
  earlyChildhoodSubjects: 'earlyChildhoodEducationSubjects',
  earlyChildhoodObjectives: 'earlyChildhoodEducationObjectives',
  prePrimarySubjects: 'prePrimaryEducationSubjects',
  prePrimaryObjectives: 'prePrimaryEducationObjectives',
  basicStudySubjects: 'basicStudySubjects',
  basicStudyObjectives: 'basicStudyObjectives',
  basicStudyContents: 'basicStudyContents',
  upperSecondarySubjects: 'upperSecondarySchoolSubjects',
  upperSecondaryObjectives: 'upperSecondarySchoolObjectives',
  upperSecondarySubjectsOld: 'upperSecondarySchoolSubjectsOld',
  upperSecondaryCoursesOld: 'upperSecondarySchoolCoursesOld',
  upperSecondarySubjectsNew: 'upperSecondarySchoolSubjectsNew',
  upperSecondaryModulesNew: 'upperSecondarySchoolModulesNew',
  upperSecondaryObjectivesNew: 'upperSecondarySchoolObjectivesNew',
  upperSecondaryContentsNew: 'upperSecondarySchoolContentsNew',
  vocationalDegrees: 'vocationalDegrees',
  vocationalUnits: 'vocationalUnits',
  vocationalObjectives: 'vocationalEducationObjectives',
  selfMotivatedSubjects: 'selfMotivatedEducationSubjects',
  selfMotivatedObjectives: 'selfMotivatedEducationObjectives',
  scienceBranches: 'branchesOfScience',
  scienceBranchObjectives: 'scienceBranchObjectives',
  prerequisites: 'prerequisites',
};
