variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

image:
  name: docker:24.0.6

stages:
  - build
  - deploy
  - cleanup

build_demo:
  stage: build
  script:
    - echo "DEMO build"
    - docker compose -f docker-compose.demo.yml build
  only:
    - test
  tags:
    - test-apps

deploy_demo:
  stage: deploy
  script:
    - echo "DEMO deploy"
    - docker compose -f docker-compose.demo.yml up -d
  only:
    - test
  tags:
    - test-apps

cleanup_demo:
  stage: cleanup
  script:
    - echo "DEMO system clean up"
    - docker system prune -a -f --volumes
  only:
    - test
  tags:
    - test-apps

build_prod:
  stage: build
  script:
    - echo "PROD build"
    - docker compose -f docker-compose.prod.yml build
  only:
    - main
  tags:
    - prod

deploy_prod:
  stage: deploy
  script:
    - echo "PROD deploy"
    - docker compose -f docker-compose.prod.yml up -d
  only:
    - main
  tags:
    - prod

cleanup_prod:
  stage: cleanup
  script:
    - echo "PROD system clean up"
    - docker system prune -a --volumes -f
  only:
    - main
  tags:
    - prod
