name: aoe-ci
services:

  aoe-web-frontend:
    build:
      context: aoe-web-frontend
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: ${AOE_WEB_FRONTEND_TAG:-aoe-web-frontend:latest}
    container_name: aoe-web-frontend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/dev/webdata:/usr/share/nginx/html/webdata
    user: "root:5606"
    depends_on:
      aoe-web-backend:
        condition: service_healthy
    ports:
      - 8282:80
      - 33344:8080
    networks:
      - default
    environment:
      - ENV=ci

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.playwright-test-runner
      args:
        PLAYWRIGHT_VERSION: ${PLAYWRIGHT_VERSION}
    networks:
      - default
    volumes:
      - ./screenshots:/screenshots
      - ./playwright-results:/playwright-results
    environment:
      - CI=true
      - GITHUB_SHA
      - GITHUB_SERVER_URL
      - GITHUB_REPOSITORY
      - GITHUB_RUN_ID
    depends_on:
      nginx:
        condition: service_started

  aoe-streaming-app:
    hostname: aoe-streaming-app
    build:
      context: aoe-streaming-app
      dockerfile: ./docker/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: ${AOE_STREAMING_APP_TAG:-aoe-streaming-app:latest}
    container_name: aoe-streaming-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - 3001:3001
    env_file:
      - path: ./aoe-streaming-app/.env.ci
    depends_on:
        localstack:
          condition: service_started

  aoe-web-backend:
    build:
      context: aoe-web-backend
      dockerfile: ./docker/Dockerfile.local
      args:
        NODE_VERSION: ${NODE_VERSION}
    image: ${AOE_WEB_BACKEND_TAG:-aoe-web-backend:latest}
    container_name: aoe-web-backend
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://aoe-web-backend:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./docker/dev/web/thumbnail/:/app/thumbnail:rw
      - ./docker/dev/web/uploads:/app/uploads:rw
      - ./docker/dev/web/webdata:/webdata:rw
      - ./docker/dev/web/webdata/htmlfolder:/webdata/htmlfolder:rw
      - ./aoe-web-backend/src:/app/src:rw
    depends_on:
      aoe-oidc-server:
        condition: service_healthy
      aoe-postgres:
        condition: service_started
      redis:
        condition: service_started
      opensearch:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - ENV=demo
    ports:
      - 3000:3000
    env_file:
      - ./aoe-web-backend/.env.ci

  redis:
    image: redis:6.2.22-alpine@sha256:c9ab371a96b057d3642be9bd71cb1b3fe97920d345dc949860578bffb3d54460
    container_name: redis
    privileged: true
    command: ["redis-server", "--requirepass", "dev_password", "--user", "devuser", "on", ">devuser_password", "~*", "+@all", "--user", "default", "off", "nopass", "nocommands"]
    restart: unless-stopped
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - ./docker/dev/redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -u redis://devuser:devuser_password@localhost:6379 ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 6379:6379

  aoe-postgres:
    image: postgres:15-alpine@sha256:3d0f7584ed7d04e27fa050d6683a74746608faf21f202be78460d679cc56461f
    container_name: aoe-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aoeuser
      POSTGRES_PASSWORD: aoepassword
      POSTGRES_DB: aoe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aoeuser -d aoe"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/init-scripts/aoe-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./docker/init-scripts/aoe-user.sql:/docker-entrypoint-initdb.d/2-init.sql
      - ./docker/dev/postgres_data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:3.7.0@sha256:44ba7ea58a319adf61c33ab16873f9ef5dbb30b291a832d375172f0b2d24e3c9
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Asfsadfsad!@2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 9200:9200
      - 9600:9600

  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    container_name: localstack 
    networks:
      default:
        aliases:
          - aoe.s3.localhost.localstack.cloud
          - aoepdf.s3.localhost.localstack.cloud
          - aoethumbnail.s3.localhost.localstack.cloud
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG="1"
      - HOSTNAME_EXTERNAL=localhost
    ports:
      - 4566:4566
    volumes:
      - ./docker/init-scripts/aws-shutdown.sh:/etc/localstack/init/shutdown.d/aws-shutdown.sh
      - ./docker/init-scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./docker/dev/localstack/S3:/host-directory

  aoe-oidc-server:
    hostname: aoe-oidc-server
    container_name: aoe-oidc-server
    image: quay.io/keycloak/keycloak:26.6.3@sha256:9b0330756022422149aa6502eb2def8cd47c6e1b000c7c65cdb13e7c0133e992
    ports:
      - '127.0.0.1:8080:8080'
    command: [ "start-dev", "--import-realm", "--health-enabled=true" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    restart: always
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  nginx:
    image: nginx:latest@sha256:5a88c9c45479443d7be2eadc894b4ed0a9801bae03d97a5760ae13b5c2005942
    container_name: nginx
    hostname: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt:ro
      - ./docker/nginx/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key:ro
    networks:
      default:
        aliases:
          - demo.aoe.fi
    depends_on:
      aoe-web-backend:
        condition: service_healthy
      aoe-web-frontend:
        condition: service_healthy
      aoe-streaming-app:
        condition: service_started

networks:
  default:
    name: aoe_ci

volumes:
  postgres_data:

