ARG PLAYWRIGHT_VERSION
FROM mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble

COPY playwright/package.json /
COPY playwright/package-lock.json /
RUN --mount=type=cache,target=/root/.npm npm ci

COPY playwright/tests /tests
COPY playwright/test-files /test-files
COPY playwright/playwright.config.ts /

ENTRYPOINT ["/usr/bin/npm", "run", "playwright:test"]
