services:
  test-oaipmh-provider:
    build:
      context: .
      dockerfile: ./oaipmh-provider/Dockerfile
    image: test-oaipmh-provider:latest
    container_name: test-oaipmh-provider
    restart: unless-stopped
    ports:
      - '8002:8002'
    env_file:
      - /environment/aoe-data-services/test/.env
    environment:
      SPRING_PROFILES_ACTIVE: 'test'
    networks:
      - network-test-oaipmh-provider

networks:
  network-test-oaipmh-provider:
    driver: bridge
