FROM mcr.microsoft.com/playwright:v1.57.0-noble@sha256:3bed4b1a12f2338642f3d8cba28e291deef3c66bd4a964bbeb3e57bbff511dbd

COPY playwright/package.json /
COPY playwright/package-lock.json /
RUN --mount=type=cache,target=/root/.npm npm ci

COPY playwright/tests /tests
COPY playwright/test-files /test-files
COPY playwright/playwright.config.ts /

ENTRYPOINT ["/usr/bin/npm", "run", "playwright:test"]

