version: '3'
services:
  provider-rest:
    build:
      context: ./provider-rest
      dockerfile: dev.Dockerfile
    image: provider-rest:latest
    container_name: provider-rest
    restart: always
    ports:
      - 8002:8002
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
    networks:
      - network-provider-dev

networks:
  network-provider-dev:
    driver: bridge
