FROM mcr.microsoft.com/playwright:v1.55.1-noble@sha256:2f29369043d81d6d69a815ceb80760f55e85f5020371ad06a4d996f18503ad1c

COPY playwright/package.json /
COPY playwright/package-lock.json /
RUN --mount=type=cache,target=/root/.npm npm ci

COPY playwright/tests /tests
COPY playwright/test-files /test-files
COPY playwright/playwright.config.ts /

ENTRYPOINT ["/usr/bin/npm", "run", "playwright:test"]

