version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: aoe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    networks:
      - aoe-network

  provider-rest:
    build:
      context: ./provider-rest
      dockerfile: Dockerfile
    image: provider-rest:latest
    container_name: provider-rest
    restart: always
    ports:
      - 8001:8001
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
    networks:
      - aoe-network

  resolver-data:
    build:
      context: ./resolver-data
      dockerfile: Dockerfile
    image: resolver-data:latest
    container_name: resolver-data
    restart: always
    ports:
      - 8002:8002
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/aoe'
    networks:
      - aoe-network

  resolver-rest:
    build:
      context: ./resolver-rest
      dockerfile: Dockerfile
    image: resolver-rest:latest
    container_name: resolver-rest
    restart: always
    ports:
      - 8003:8003
    depends_on:
      - resolver-data
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      AOE_RESOLVER-DATA_URL: 'http://resolver-data:8002'
    networks:
      - aoe-network

networks:
  aoe-network:
