FROM node:20-alpine3.22@sha256:6178e78b972f79c335df281f4b7674a2d85071aae2af020ffa39f0a770265435

WORKDIR /app

COPY package.json package-lock.json ./
COPY vendor ./vendor/

RUN npm ci

RUN apk add --no-cache \
    fontconfig \
    libreoffice \
    ttf-dejavu \
    ttf-freefont \
    ttf-liberation

COPY docker ./docker/

RUN mkdir -p /app/h5p && \
    unzip /app/docker/h5p.zip -d /app/h5p

# Copy source files into application directory
COPY --chown=app:app . /app

EXPOSE 3000

RUN npm run build-ts

COPY ./src/search/aoemapping.json /app
COPY ./src/search/aoecollectionmapping.json /app

ENTRYPOINT ["./docker/entrypoint.sh"]
