FROM node:20-alpine3.22@sha256:4d04c7fd781fe4f1bab9e412eb54de2882226e1e2cf3ba41206f7edbad5892dd

WORKDIR /app

COPY package.json package-lock.json ./
COPY vendor ./vendor/

RUN npm ci

RUN apk add --no-cache \
    fontconfig \
    libreoffice \
    ttf-dejavu \
    ttf-freefont \
    ttf-liberation

COPY docker ./docker/

RUN mkdir -p /app/h5p && \
    unzip /app/docker/h5p.zip -d /app/h5p

# Copy source files into application directory
COPY --chown=app:app . /app

EXPOSE 3000

RUN npm run build-ts

COPY ./src/search/aoemapping.json /app
COPY ./src/search/aoecollectionmapping.json /app

ENTRYPOINT ["./docker/entrypoint.sh"]
