FROM node:20-alpine3.22@sha256:9a6da5b3b736cc5ccc3bc11312cb83d0dae84705f00da92ae420d76a15a9da6f

WORKDIR /app

COPY package.json package-lock.json ./
COPY vendor ./vendor/

RUN npm ci

RUN apk add --no-cache \
    fontconfig \
    libreoffice \
    ttf-dejavu \
    ttf-freefont \
    ttf-liberation

COPY docker ./docker/

RUN mkdir -p /app/h5p && \
    unzip /app/docker/h5p.zip -d /app/h5p

# Copy source files into application directory
COPY --chown=app:app . /app

EXPOSE 3000

RUN npm run build-ts

COPY ./src/search/aoemapping.json /app
COPY ./src/search/aoecollectionmapping.json /app

ENTRYPOINT ["./docker/entrypoint.sh"]
