version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: aoe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data

  resolver:
    image: resolver:latest
    container_name: resolver
    restart: always
    ports:
      - 8002:8002
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/aoe'
