FROM node:12.4.0-stretch as front-builder
WORKDIR /app
COPY package.json /app/
COPY package-lock.json /app/
RUN npm install
COPY ./ /app/

RUN npm run build-demo

FROM openresty/openresty:1.13.6.2-stretch
COPY --from=front-builder /app/dist/ /usr/share/nginx/html/
COPY ./docker/server.conf /etc/nginx/conf.d/default.conf
