name: Push image
description: Upload built image to AWS ECR
inputs:
  username:
    description: ghcr.io username
    required: true
  password:
    description: ghcr.io password
    required: true
  aws-arn:
    description: aws util arn
    required: true


runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
      with:
        role-to-assume: ${{ inputs.aws-arn }}
        role-session-name: aoe-runner-ecr-push
        aws-region: eu-west-1

    - name: 03-push-image.sh
      working-directory: ./
      shell: bash
      run: ./deploy-scripts/03-push-image.sh
