version: "3.8"
services:
  aoe-streaming-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: aoe-streaming-app:latest
    container_name: aoe-streaming-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - /environment/aoe-streaming-app/.env
    networks:
      - aoe-streaming-network

networks:
  aoe-streaming-network:
    driver: bridge
