version: "3.8"
services:
  aoe-streaming-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: aoe-streaming-app:latest
    container_name: aoe-streaming-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    networks:
      - aoe-streaming-network

networks:
  aoe-streaming-network:
    driver: bridge
