variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

image: docker:24.0.6

stages:
  - build
  - deploy
  - cleanup

build_analytics:
  stage: build
  script:
    - echo "PROD build"
    - docker-compose -f docker-compose.prod.yml build
  only:
    - main
  tags:
    - prod-oaipmh

deploy_analytics:
  stage: deploy
  script:
    - echo "PROD deploy"
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - main
  tags:
    - prod-oaipmh

cleanup_analytics:
  stage: cleanup
  script:
    - echo "PROD system clean up"
    - docker system prune -a -f --volumes
  only:
    - main
  tags:
    - prod-oaipmh
