services:
  aoe-etl-processor:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: .
      dockerfile: ./service-etl-processor/Dockerfile
    image: aoe-etl-processor:latest
    container_name: aoe-etl-processor
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - ./service-etl-processor/.env
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - network-analytics

networks:
  network-analytics:
    external: true
    name: network-analytics
