name: Build and test master
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  actions: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_dev:
    needs: build 
    uses: ./.github/workflows/deploy_dev.yml
    secrets: inherit
