name: Scheduled Renovate Execution
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0/20 * * * *'

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./.github/actions/app-token-exporter
        id: app-token
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8ac70de2fe55752c573155866e30735411e3b61c # v41.0.22
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: 'Opetushallitus/aoe'
          RENOVATE_AUTODISCOVER_FILTER: 'Opetushallitus/aoe'
