export const qaEnvironment = {
  production: true,
  loginUrl: 'https://qa.aoe.fi/api',
  backendUrl: 'https://qa.aoe.fi/api/v1',
  backendUrlV2: 'https://qa.aoe.fi/api/v2',
  embedBackendUrl: 'https://qa.aoe.fi/embed',
  statisticsBackendUrl: 'https://qa.aoe.fi/api/v2/statistics/prod',
  frontendUrl: 'https://qa.aoe.fi',
  newERLSKey: 'aoe.new-educational-resource',
  koodistoUrl: 'https://qa.aoe.fi/ref/api/v1',
  sessionCookie: 'connect.sid',
  userdataKey: 'aoe.userdata',
  cookieSettingsCookie: 'aoe.cookies',
  searchParams: 'aoe.searchParams',
  searchResults: 'aoe.searchResults',
  usedFilters: 'aoe.usedFilters',
  editMaterial: 'aoe.editMaterial',
  title: '- Avointen oppimateriaalien kirjasto (qa.aoe.fi)',
  collection: 'aoe.collection',
  collectionSearchParams: 'aoe.collectionSearchParams',
  collectionSearchResults: 'aoe.collectionSearchResults',
  sessionMaxAge: 60 * 60 * 8 * 1000, // 8 hours
  disableForms: 'aoe.disableForms',
  disableLogin: 'aoe.disableLogin'
}
